version: '3'

volumes:
  soda-inventory-data:
    driver: local

services:
  app:
    image: ambientum/php:7.3-nginx
    container_name: app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - soda-inventory-data:/data/db
  web:
    build: frontend/
    ports: 
      - "8080:8080"
    
