version: '3'
networks:
  mongo-compose-network:
    driver: bridge

volumes:
  soda-inventory-data:
    driver: local

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
      - "8081:8081"
    links:
      - mongo
    networks:
      - mongo-compose-network
  mongo-express:
    image: mongo-express
    ports:
      - 8082:8082
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASS}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - soda-inventory-data:/data/db
    networks:
      - mongo-compose-network
